export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';